apiVersion: v1
kind: Service
metadata:
  name: autodeploy01
  namespace: namespace-workflow-1716987470864
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: autodeploy01
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000